export const Footer = () => {
  return (
    <footer className="sticky bottom-0 z-10 bg-white/80 backdrop-blur-sm border-t border-gray-100 py-2">
      <div className="container mx-auto text-center">
        <span className="text-gray-500 text-xs">
          Summary generated by an AI duck
        </span>
      </div>
    </footer>
  );
};